# Generated by Django 4.1 on 2022-08-22 00:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_service',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_service',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='track',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('PAYED', 'PAYED'), ('DONE', 'Done'), ('CANCELED', 'CANCELED')], default='NEW', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
    ]
