# Generated by Django 4.1 on 2022-08-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_date_order_delivery_service_order_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_format', models.TextField(default="<a href='{url}'>{name}</a><img src='{image}'/><p>{count} x {price} {totalPrice}</p><hr>", verbose_name='Item mail format')),
                ('new_order_mail_title', models.CharField(default='Order #{number} payed', max_length=100, verbose_name='Title of email')),
                ('new_order_mail', models.TextField(default='<h1>New order #{number}</h1><p>Thanks for order</p>{items}<p>Price: {total_price}</p><p>With love your-site-name</p>', verbose_name='New order email')),
                ('order_payed_mail_title', models.CharField(default='Order #{number} payed', max_length=100, verbose_name='Title of email')),
                ('order_payed_mail', models.TextField(default='<h1>Order #{number} payed</h1><p>Your order payed</p>{items}<p>Price: {total_price}</p>{track}<p>With love your-site-name</p>', verbose_name='Order payed email')),
            ],
            options={
                'verbose_name': 'Order settings',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('PAYED', 'PAYED'), ('DONE', 'DONE'), ('CANCELED', 'CANCELED')], default='NEW', max_length=15, verbose_name='Status'),
        ),
    ]
