# Generated by Django 4.1 on 2022-08-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordersettings_order_email_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersettings',
            name='novaposhta_description',
            field=models.CharField(default='Order #{number}', max_length=36, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='novaposhta_weight',
            field=models.PositiveIntegerField(default=1, verbose_name='Parsel weight'),
        ),
    ]
