# Generated by Django 4.1 on 2022-08-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordersettings_novaposhta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersettings',
            name='new_order_mail_title',
            field=models.CharField(default='New order #{number}', max_length=100, verbose_name='Title for new order email'),
        ),
        migrations.AlterField(
            model_name='ordersettings',
            name='novaposhta_description',
            field=models.CharField(default='Order {number}', max_length=36, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ordersettings',
            name='order_payed_mail_title',
            field=models.CharField(default='Order #{number} payed', max_length=100, verbose_name='Title for payed order email'),
        ),
    ]
