# Generated by Django 4.1 on 2023-02-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_ordersettings_new_order_mail_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_data',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
