# Generated by Django 3.2 on 2022-06-06 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('url', models.CharField(help_text='Example: https://google.com or /testPage', max_length=200, validators=[django.core.validators.URLValidator], verbose_name='URL')),
                ('target', models.CharField(choices=[('BL', '_blank'), ('SE', '_self')], default='SE', max_length=2, verbose_name='Url type')),
                ('position', models.CharField(choices=[('FO', 'footer'), ('HE', 'header')], max_length=2, verbose_name='Position')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('weight', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Element',
                'verbose_name_plural': 'Elements',
                'ordering': ['weight'],
            },
        ),
    ]
