# Generated by Django 3.2 on 2022-06-24 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='url',
            field=models.CharField(help_text='Example: https://google.com/ or /testPage/', max_length=200, validators=[django.core.validators.URLValidator], verbose_name='URL'),
        ),
    ]
