# Generated by Django 3.2 on 2022-06-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_element_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='element',
            name='name_uk',
            field=models.CharField(max_length=150, null=True, verbose_name='Name'),
        ),
    ]
