# Generated by Django 4.1 on 2022-08-22 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20220625_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='element',
            name='name_uk',
        ),
    ]
