# Generated by Django 4.1 on 2022-08-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('answer', models.TextField(blank=True, verbose_name='Answer')),
                ('answered', models.BooleanField(default=False, verbose_name='Answered')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['answered'],
            },
        ),
        migrations.CreateModel(
            name='HelperSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_feedback_len', models.PositiveIntegerField(default=20, help_text='Minimum length of feedback text')),
                ('max_feedback_len', models.PositiveIntegerField(default=500, help_text='Maximum length of feedback text')),
                ('feedback_email_title', models.CharField(default='Answer on question', max_length=50, verbose_name='Title of email')),
                ('feedback_email', models.TextField(default='<h4>Given answer to your question</h4><br><p>Your question:</p><span>{question}</span><br><p>Answer:</p><span>{answer}</span><p>With love...</p>', verbose_name='Feedback email')),
            ],
            options={
                'verbose_name': 'Helper Configuration',
            },
        ),
    ]
