# Generated by Django 3.2 on 2022-06-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpage',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Draft'),
        ),
    ]
